export const types = {
	PUT_CURRENT_DATA: 'GET_CURRENT_DATA',
	PUT_FIVE_DATA: 'PUT_FIVE_DATA',
	DROP_DOWN: 'DROP_DOWN',
	INPUT_HANDLER: 'INPUT_HANDLER',
	INPUT_SEARCH: 'INPUT_SEARCH',
	SELECT_CURRENCY: 'SELECT_CURRENCY',
	RECALCULATE_WHEN_SELECTED: 'RECALCULATE_WHEN_SELECTED',
	SELECT_FAVORITE: 'SELECT_FAVORITE',
	REMOVE_SELECT_FAVORITE: 'REMOVE_SELECT_FAVORITE',
	CHANGE_BOX: 'CHANGE_BOX'
};
